[package]
name = "strum"
version = "0.1.0"
authors = ["Peter Glotfelty <peglotfe@microsoft.com>"]
license = "MIT"

description = "Helpful macros for working with enums and strings"
keywords = ["enum", "string", "macros", "proc-macros"]
categories = ["development-tools::procedural-macro-helpers", "parsing"]

documentation = "https://github.com/Peternator7/strum"
homepage = "https://github.com/Peternator7/strum"
readme = "../README.md"

[dev-dependencies]
strum_macros = { git = "https://github.com/Peternator7/strum" }